name: Release

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Run on pushes to production branch
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Checkout release branch
        run: |
          git checkout -b release/$(./version.sh)

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Commit dist/
        run: |
          git add --all
          git commit -m "Release: v$(./version.sh)"

      - name: Push release branch
        run: |
          git push origin release/$(./version.sh)

      - name: Create release
        run: |
          git tag v$(./version.sh)
          git push origin --tags
